cmake_minimum_required(VERSION 3.10 FATAL_ERROR)
project(cpp)

add_subdirectory(calibration_from_file)
add_subdirectory(code_reader_from_file)
add_subdirectory(get_first_pixel)
add_subdirectory(image_region_from_file)
add_subdirectory(nion_point_cloud)
add_subdirectory(open_camera)
add_subdirectory(threshold_from_file)
