<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <ImplicitUsings>false</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RuntimeIdentifiers>
            win-x86;win-x64
        </RuntimeIdentifiers>
        <UseWindowsForms>true</UseWindowsForms>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="IDSImaging.Peak.API" Version="1.*"/>
        <PackageReference Include="IDSImaging.Peak.Common" Version="1.*"/>
        <PackageReference Include="IDSImaging.Peak.ICV" Version="1.*"/>
    </ItemGroup>
</Project>
